#!/usr/bin/env bash
##( header
#
# Shared helpers for the zap-sh conformance suite.
#
# The conformance suite pins the byte-for-byte output of `zap-sh init`
# (the bash oracle) so that a second implementation (the JavaScript
# generator) can be verified against the exact same fixtures. See SPEC.md
# and test/conformance/README.md.
#
# Sourced by:
#   - test/conformance/gen-expected.sh  (regenerates expected/*.sh)
#   - test/test-conformance.sh          (the runner listed in tests.txt)
##) header

##( paths
# Resolve conformance + project directories relative to this file, so the
# helpers work regardless of the caller's working directory.
CONF_DIR="$(cd -P "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONF_FIXTURES_DIR="$CONF_DIR/fixtures"
CONF_EXPECTED_DIR="$CONF_DIR/expected"
CONF_PROJECT_ROOT="$(cd -P "$CONF_DIR/../.." && pwd)"
CONF_ZAP="$CONF_PROJECT_ROOT/zap-sh"
##) paths

##( helpers

# conf_have_jq -> returns 0 if jq is available, 1 otherwise.
conf_have_jq() { command -v jq >/dev/null 2>&1; }

# conf_build_args <fixture.json>
#   Populates the global array CONF_ARGS with the `zap-sh init` arguments
#   described by the fixture, and CONF_NAME with the fixture name.
#   The caller appends its own `-o <path>` (output path never affects the
#   generated bytes, only where they are written).
#
#   Fixture schema:
#     { "name": str, "template": "basic"|"enhanced", "project": str,
#       "year": str, "license"?: str, "variables"?: { key: value, ... } }
conf_build_args() {
  local fixture="$1"
  local template project year license

  CONF_NAME=$(jq -r '.name' "$fixture")
  template=$(jq -r '.template' "$fixture")
  project=$(jq -r '.project' "$fixture")
  year=$(jq -r '.year // empty' "$fixture")
  license=$(jq -r '.license // empty' "$fixture")

  CONF_ARGS=("$project" "-t" "$template")
  [[ -n "$year" ]] && CONF_ARGS+=("--year=$year")
  [[ -n "$license" ]] && CONF_ARGS+=("--license=$license")

  # Variables become --key=value flags, preserving the fixture's key order
  # (jq keeps JSON object insertion order; so does JSON.parse in JS), which
  # matters because substitution precedence is order-sensitive (see SPEC.md).
  local kv
  while IFS= read -r kv; do
    [[ -n "$kv" ]] && CONF_ARGS+=("--$kv")
  done < <(jq -r '.variables // {} | to_entries[] | "\(.key)=\(.value)"' "$fixture")
}

# conf_generate <fixture.json> <output-path>
#   Runs the bash oracle for a fixture and writes the generated script to
#   <output-path>, overwriting it. Generation always targets a fresh path
#   inside a private temp dir (never <output-path> directly) so that
#   `zap-sh init` never sees an existing file and never triggers its
#   interactive overwrite prompt (which would otherwise cancel silently on
#   EOF and leave stale output). Returns the oracle's exit code.
conf_generate() {
  local fixture="$1" out="$2"
  conf_build_args "$fixture"

  local td gen rc
  td=$(mktemp -d)
  gen="$td/gen.sh"
  ZAP_DEV=true "$CONF_ZAP" init "${CONF_ARGS[@]}" -o "$gen" >/dev/null 2>&1
  rc=$?
  [[ $rc -eq 0 ]] && cp "$gen" "$out"
  rm -rf "$td"
  return $rc
}

##) helpers
