// @budhash/zap-sh — JavaScript generator for zap-sh scripts.
//
// This is a faithful port of the bash `zap-sh init` generation path. The bash
// script is the reference oracle; for identical inputs this produces the exact
// same bytes. See ../../SPEC.md for the contract and ../../test/conformance for
// the shared fixtures that verify parity.
import { TEMPLATES, LICENSES } from './templates.generated.js';

const SHEBANG = '#!/usr/bin/env bash';

// Section emit order (SPEC §3 / _SECTIONS in zap-sh).
const SECTIONS = ['header', 'configuration', 'metadata', 'globals', 'helpers', 'app', 'core'];

const NAME = 'zap-sh';
const PROJECT_RE = /^[a-zA-Z0-9_-]+$/;
const VARNAME_RE = /^[a-zA-Z_][a-zA-Z0-9_]*$/;

// --- substitution -----------------------------------------------------------

// Replace every occurrence of {{key}} with value, for each [key, value] pair in
// order, across the whole buffer. Mirrors bash apply_variables: sequential and
// whole-buffer, so a token introduced by one variable's value is resolved by a
// LATER variable (never an earlier one). See SPEC §4.
export function substitute(content, pairs) {
  let result = content;
  for (const [key, value] of pairs) {
    result = result.split(`{{${key}}}`).join(value);
  }
  return result;
}

// Extract a section including its markers, from the first `##( name` line to the
// first following `##) name` line (exact-line match). Mirrors
// `sed -n '/^##( name$/,/^##) name$/p'`. Returns null if the section is absent.
export function extractSection(templateText, name) {
  const lines = templateText.split('\n');
  const open = `##( ${name}`;
  const close = `##) ${name}`;
  let start = -1;
  for (let i = 0; i < lines.length; i++) {
    if (lines[i] === open) { start = i; break; }
  }
  if (start === -1) return null;
  for (let i = start; i < lines.length; i++) {
    if (lines[i] === close) return lines.slice(start, i + 1).join('\n');
  }
  return null;
}

// --- licenses ---------------------------------------------------------------

// Available license codes: basenames lowercased and sorted (SPEC §7).
export function listLicenses() {
  return Object.keys(LICENSES).map((n) => n.toLowerCase()).sort();
}

// Available template names.
export function listTemplates() {
  return Object.keys(TEMPLATES);
}

// Resolve a license code case-insensitively to its original-case basename, or
// null if not found (mirrors `find -iname`).
function resolveLicenseName(code) {
  const lower = String(code).toLowerCase();
  for (const name of Object.keys(LICENSES)) {
    if (name.toLowerCase() === lower) return name;
  }
  return null;
}

// --- generation -------------------------------------------------------------

function hasVar(pairs, key) {
  return pairs.some(([k]) => k === key);
}

/**
 * Generate a zap-sh script.
 *
 * @param {object} opts
 * @param {string} opts.template  "basic" | "enhanced"
 * @param {string} opts.project   project name (becomes {{app}}); [a-zA-Z0-9_-]+
 * @param {object} [opts.variables]  extra {{key}} values; key order is significant
 * @param {string} [opts.license]  license code: "mit" | "apache" | "gpl"
 * @param {string|number} [opts.year]  pins {{year}} (SPEC §6); defaults to current year
 * @param {string} [opts.output]  output filename (does not affect content)
 * @returns {{ filename: string, content: string }}
 */
export function generate(opts = {}) {
  const { template, project, variables = {}, license, year, output } = opts;

  if (!template || !Object.prototype.hasOwnProperty.call(TEMPLATES, template)) {
    throw new Error(`invalid template: '${template}' (available: ${listTemplates().join(', ')})`);
  }
  if (typeof project !== 'string' || !PROJECT_RE.test(project)) {
    throw new Error(`invalid project name: '${project}' (letters/numbers/hyphens/underscores only)`);
  }
  for (const key of Object.keys(variables)) {
    if (!VARNAME_RE.test(key)) {
      throw new Error(`invalid variable name: '${key}' (must start with letter/underscore, contain only letters/numbers/underscore)`);
    }
  }

  const resolvedYear = String(year !== undefined && year !== null && year !== '' ? year : new Date().getFullYear());

  // User variables, in the same order the bash CLI collects them: year, then
  // license, then the caller's variables (insertion order preserved).
  const userVars = [];
  if (year !== undefined && year !== null && year !== '') userVars.push(['year', resolvedYear]);
  if (license !== undefined && license !== null && license !== '') userVars.push(['license', String(license)]);
  for (const [k, v] of Object.entries(variables)) userVars.push([k, String(v)]);

  // Computed defaults (SPEC §4.1), appended after user variables.
  const baseDefaults = [
    ['app', project],
    ['year', resolvedYear],
    ['detail', `Generated by ${NAME}`],
    ['description', `Generated by ${NAME} template`],
  ];
  if (!hasVar(userVars, 'author')) baseDefaults.push(['author', 'anonymous']);
  if (!hasVar(userVars, 'version')) baseDefaults.push(['version', '0.1.0']);
  if (!hasVar(userVars, 'email')) baseDefaults.push(['email', '']);

  // License: name always defaults to "MIT License"; content only when a license
  // is selected. The content is pre-substituted with the variable map WITHOUT
  // license_name/license_content (matches apply_license). See SPEC §7.
  let licenseName = 'MIT License';
  let licenseContent = '';
  if (license !== undefined && license !== null && license !== '') {
    const resolved = resolveLicenseName(license);
    if (!resolved) {
      throw new Error(`license file not found: ${license} (available: ${listLicenses().join(' ')})`);
    }
    licenseName = `${resolved} License`;
    licenseContent = substitute(LICENSES[resolved], [...userVars, ...baseDefaults]);
  }

  const fullDefaults = [...baseDefaults, ['license_name', licenseName]];
  // Empty license_content is NOT added, so {{license_content}} stays literal
  // where a template references it (the enhanced header) — matching the oracle.
  if (licenseContent !== '') fullDefaults.push(['license_content', licenseContent]);

  const allVars = [...userVars, ...fullDefaults];

  // Assemble: fresh shebang, then each present section substituted, each
  // terminated by exactly one newline (SPEC §5).
  const templateText = TEMPLATES[template];
  let content = SHEBANG + '\n';
  for (const section of SECTIONS) {
    const sectionText = extractSection(templateText, section);
    if (sectionText !== null && sectionText !== '') {
      content += substitute(sectionText, allVars) + '\n';
    }
  }

  const filename = output || `${project}.sh`;
  return { filename, content };
}

export default { generate, substitute, extractSection, listTemplates, listLicenses };
